### ISSUE TITLE
The year at the bottom of the website is outdated

### ISSUE THREAD

**Issue by eam17** [eam17/resume-website#1]
Currently, the bottom of the website reads "Molostvova 2019"
Change the year to 2019
![image](https://user-images.githubusercontent.com/26548355/68690494-1d8c4800-0540-11ea-979b-f7c9806a9ab5.png)

**Comment by eam17** [comment]
Can I work on this issue?

**Comment by eam17** [comment]
@eam17 Go for it!

**Comment by eam17** [comment]
Hi, I'd like to work on this issue

**Comment by AnonStudentContributer** [comment]
Can I work on this issue?

**Comment by eam17** [comment]
@AnonStudentContributer Go for it!
