### ISSUE TITLE
Extra period in the education heading

### ISSUE THREAD

**Issue by eam17** [eam17/resume-website#9]
Remove the period at the end of my major
![image](https://user-images.githubusercontent.com/26548355/68702073-1ff99c80-0556-11ea-8d55-e1b2b73d211a.png)
![image](https://user-images.githubusercontent.com/26548355/68702086-28ea6e00-0556-11ea-9953-0b79deb9ed79.png)

**Comment by amshay63** [comment]
Can I try this one?

**Comment by eam17** [comment]
@amshay63 Sure!
